ServicePortal/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('mande.urls')),
    url(r'^admin/', admin.site.urls),
]

mande/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'mande'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<opp_id>[\d]+)/signup$', views.signup, name='signup'),
    url(r'^(?P<opp_id>[0-9]+)/results/$', views.results, name='results'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mande/models.py
from django.db import models
from datetime import datetime

TYPES = (
    (1,'Babysitting'),
    (2,'Cleaning'),
    (3,'Commerce'),
    (4,'IT'),
    (5,'Tutoring'),
    (6,'Ushering'),
    (7,'MISC'),
)
class Opportunity(models.Model):
    opportunity_id = models.AutoField(primary_key=True)
    opportunity_title = models.CharField(max_length=20)
    opportunity_details = models.CharField(max_length=200)
    image = models.IntegerField('Opportunity Type',choices=TYPES,default=1)
    opportunity_requirements = models.CharField(max_length=200, default = "None")
    hours_earned = models.PositiveIntegerField(default=1)
    email = models.EmailField(max_length=100)
    date = models.DateTimeField('date')
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    class Meta:
        verbose_name_plural = "opportunities"

    def __str__(self):
        return self.opportunity_title


class Volunteer(models.Model):
    opportunity = models.ForeignKey(Opportunity, on_delete=models.CASCADE)
    volunteer_name = models.CharField(max_length=100)
    volunteer_email = models.EmailField(max_length=100)
    volunteer_grade = models.PositiveIntegerField(default=1)
    volunteer_detail = models.CharField(max_length=200, default = "N/A")

    def __str__(self):
        return self.volunteer_name

mande/forms.py
from django.forms import ModelForm
from .models import Volunteer

class VolunteerForm(ModelForm):
    class Meta:
        model = Volunteer
        exclude = ['opportunity']

    def __init__(self, *args, **kwargs):
        super(VolunteerForm, self).__init__(*args, **kwargs)
        #for field in iter(self.fields):
        self.fields['volunteer_name'].widget.attrs.update({
            'id': 'name',
            'class': 'form-control'
        })
        self.fields['volunteer_email'].widget.attrs.update({
            'id': 'email',
            'class': 'form-control'
        })
        self.fields['volunteer_grade'].widget.attrs.update({
            'id': 'grade',
            'class': 'form-control'
        })
        self.fields['volunteer_detail'].widget.attrs.update({
            'id': 'detail',
            'class': 'form-control'
        })

mande/views.py
from django import forms
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Opportunity, Volunteer
from .forms import VolunteerForm
from django.core.mail import send_mail

def home(request):
    opportunity = Opportunity.objects.all()
    form = VolunteerForm(request.POST or None)
    return render(request, 'mande/home.html', {'opplist': opportunity, 'form':form})

def signup(request, opp_id):
    opportunity = Opportunity.objects.all()
    select_opportunity = Opportunity.objects.get(pk=opp_id)
    form = VolunteerForm(request.POST or None)
    if form.is_valid():
        vol = form.save(commit=False)
        vol.opportunity = select_opportunity
        send_mail('Potential Volunteer for '+select_opportunity.opportunity_title, 'Hello, \nThe Service Portal is pleased to inform you that '+ vol.volunteer_name +' has signed up for your service opportunity: '+select_opportunity.opportunity_title+'\nYou can contact '+ vol.volunteer_name +' at '+ vol.volunteer_email +'\nPlease let us know if there are any issues, \nMost sincerely, \nThe Service Portal', 'stuco@stuco.students.logoscambodia.org', [select_opportunity.email])
        vol.save()
        #return HttpResponseRedirect('results')
    return HttpResponseRedirect(reverse('mande:results', args=(opp_id)))

def results(request, opp_id):
    opportunity = get_object_or_404(Opportunity, pk=opp_id)
    return render(request, 'mande/results.html', {'opp' : opportunity})

mande/templates/mande/home.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Logos Service Portal</title>
    <link rel="shortcut icon" href="/static/home/favicon.ico" type="img/x-icon">

    <link href="/static/home/css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="/static/home/css/metastyle.css" rel="stylesheet" type="text/css">
    <link href="/static/home/css/animate.css" rel="stylesheet" type="text/css">

    <link href="/static/home/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
</head>

<body>

  <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                  <i class="fa fa-bars"></i>
              </button>
              <a class="navbar-brand page-scroll" href="#page-top">
                  <!--<i class="fa fa-play-circle"></i>  <span class="light">Create an</span> Account
              </a>-->
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
              <ul class="nav navbar-nav">
                  <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                  <li class="hidden">
                      <a href="#page-top"></a>
                  </li>
                  <li>
                      <a class="page-scroll" href="#download">Opportunities</a>
                  </li>
                  <li>
                      <a class="page-scroll" href="#contact">Contact</a>
                  </li>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>

  <div style="overflow:hidden;">
    <header class="header" id="header">
    	<div class="container">
      	<figure class="logo animated fadeInDown delay-07s">
        	<a href="#"><img src="/static/home/img/portal.png" alt=""></a>
        </figure>
        <h1 class="animated fadeInDown delay-07s">Service Hour Portal</h1>
        <ul class="we-create animated fadeInUp delay-1s">
        	<li>A free, responsive, service hour tracker.</li>
        </ul>
        <a href="#opportunities" class="btn btn-circle page-scroll animated fadeInUp delay-1s">
          <i class="fa fa-angle-double-down animated"></i>
        </a>
      </div>
    </header>
  </div>

  <section id="opportunities" class="content-section text-center">
    <h1>Available Opportunities</h1>
    <div class="container">
      {% if opplist %}
       <div class="row">
        {% for x in opplist %}
         <div class="col-lg-4 col-sm-6 text-center marginB">
            <div class="hovereffect">
                {% if x.image = 1 %}
                      <img class="img-responsive" src="/static/home/img/Babysitting.png" alt="">
                {% elif x.image = 2 %}
                      <img class="img-responsive" src="/static/home/img/Cleaning.png" alt="">
                {% elif x.image = 3 %}
                      <img class="img-responsive" src="/static/home/img/Commerce.png" alt="">
                {% elif x.image = 4 %}
                      <img class="img-responsive" src="/static/home/img/IT.png" alt="">
                {% elif x.image = 5 %}
                      <img class="img-responsive" src="/static/home/img/Tutoring.png" alt="">
                {% elif x.image = 6 %}
                      <img class="img-responsive" src="/static/home/img/Ushering.png" alt="">
                {% else %}
                      <img class="img-responsive" src="/static/home/img/MISC.png" alt="">        
                {% endif %}
                 <div class="overlay">
                    <h2>{{x.opportunity_title}}</h2>
                    <p class="icon-links">
                    <a data-toggle="modal" href="#{{x.opportunity_title|cut:" " }}s" class="button"><span class="glyphicon glyphicon-bookmark"></span> </a>
                    <a data-toggle="modal" href="#{{x.opportunity_title|cut:" " }}" class="button"><span class="glyphicon glyphicon-info-sign"></span> </a>
                    </p>
                 </div>
            </div>
          </div>
         {% endfor %}
       </div>
      {% endif %}
     </div>
     <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  </section>

  {% if opplist %}
    {% for x in opplist %}
      <div class="modal fade" id="{{x.opportunity_title|cut:" " }}" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4>{{x.opportunity_title}} <span class="glyphicon glyphicon-briefcase"></span></h4>
            </div>
            <div class="modal-body modalText">
             <ul style="list-style-type:none">
                <li>
                   <h5> Opportunity Details <span class="glyphicon glyphicon-book"></span></h5>
                   <ul style = "list-style-type:none">
                      <li>{{x.opportunity_details}}</li>
                   </ul>
                </li>
                <li>
                   <h5> Opportunity Requirements <span class="glyphicon glyphicon-exclamation-sign"></span></h5>
                   <ul style = "list-style-type:none">
                      <li>{{x.opportunity_requirements}}</li>
                   </ul>
                </li>
                <li>
                   <h5> Hours Earned  <span class="glyphicon glyphicon-time"></span></h5>
                   <ul style = "list-style-type:none">
                      <li> {{x.hours_earned}}</li>
                   </ul>
                </li>
             </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="{{x.opportunity_title|cut:" " }}s" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4>Sign up <span class="glyphicon glyphicon-envelope"></span></h4>
            </div>
            <div class="modal-body modalText">
              <form id="signup" action="{% url 'mande:signup' opp_id=x.opportunity_id %}" method="post">
                  {% csrf_token %}
                  {{form}}
                  <input type="hidden" id="reciever" value="{{x.email}}">
                  <button type="submit" class="btn btn-default">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  {% endif %}
       <script src="/static/home/js/jquery.js"></script>
       <script src="/static/home/js/contact.js"></script>
       <script src="/static/home/js/bootstrap.min.js"></script>
       <script src="/static/home/js/jquery.easing.min.js"></script>
       <script src="/static/home/js/grayscale.js"></script>
   </body>
</html>

mande/templates/mande/results.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Logos Service Portal</title>
    <link rel="shortcut icon" href="/static/home/favicon.ico" type="img/x-icon">

    <link href="/static/home/css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="/static/home/css/metastyle.css" rel="stylesheet" type="text/css">
    <link href="/static/home/css/animate.css" rel="stylesheet" type="text/css">

    <link href="/static/home/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
</head>

<body>

  <section id="opportunities" class="content-section text-center">
    <br><br><br><br><br><br><br>
      <h1 class = "customheader">Thank you!</h1>
      <h3> You have successfully signed up for </h3>
      <h3>{{opp.opportunity_title}}</h3>
      <a href="{% url 'mande:home' %}" class="btn btn-default btn-custom btn-lg" role="button">Click Here To Go Back To The Homepage</a>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  </section>

       <script src="/static/home/js/jquery.js"></script>
       <script src="/static/home/js/bootstrap.min.js"></script>
       <script src="js/jqBootstrapValidation.js"></script>
       <script src="/static/home/js/contact.js"></script>
       <script src="/static/home/js/jquery.easing.min.js"></script>
       <script src="/static/home/js/grayscale.js"></script>

   </body>
</html>